"""add_maintenance_keywords_headers

Revision ID: 594efba8772b
Revises: 10c837b07bd4
Create Date: 2026-04-12 19:32:55.414081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594efba8772b'
down_revision: Union[str, None] = '10c837b07bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('custom_headers', sa.Text(), nullable=True))
    op.add_column('endpoints', sa.Column('custom_body', sa.Text(), nullable=True))
    op.add_column('endpoints', sa.Column('expected_status_code', sa.Integer(), nullable=True))
    op.add_column('endpoints', sa.Column('keyword', sa.String(length=255), nullable=True))
    op.add_column('endpoints', sa.Column('keyword_type', sa.String(length=20), nullable=True))
    op.add_column('endpoints', sa.Column('maintenance_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('endpoints', sa.Column('maintenance_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('endpoints', sa.Column('maintenance_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('endpoints', sa.Column('maintenance_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'maintenance_reason')
    op.drop_column('endpoints', 'maintenance_end')
    op.drop_column('endpoints', 'maintenance_start')
    op.drop_column('endpoints', 'maintenance_active')
    op.drop_column('endpoints', 'keyword_type')
    op.drop_column('endpoints', 'keyword')
    op.drop_column('endpoints', 'expected_status_code')
    op.drop_column('endpoints', 'custom_body')
    op.drop_column('endpoints', 'custom_headers')
    # ### end Alembic commands ###
