"""add_ssl_and_status_pages

Revision ID: 8776f306f4f7
Revises: 090f9596ddbf
Create Date: 2026-04-05 19:49:04.174028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8776f306f4f7'
down_revision: Union[str, None] = '090f9596ddbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_pages_slug'), 'status_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_status_pages_user_id'), 'status_pages', ['user_id'], unique=False)
    op.create_table('ssl_certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssl_certificates_endpoint_id'), 'ssl_certificates', ['endpoint_id'], unique=False)
    op.create_table('status_page_endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status_page_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_page_id'], ['status_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_page_endpoints_status_page_id'), 'status_page_endpoints', ['status_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_page_endpoints_status_page_id'), table_name='status_page_endpoints')
    op.drop_table('status_page_endpoints')
    op.drop_index(op.f('ix_ssl_certificates_endpoint_id'), table_name='ssl_certificates')
    op.drop_table('ssl_certificates')
    op.drop_index(op.f('ix_status_pages_user_id'), table_name='status_pages')
    op.drop_index(op.f('ix_status_pages_slug'), table_name='status_pages')
    op.drop_table('status_pages')
    # ### end Alembic commands ###
